import { useEffect, useState } from 'react'

import { IVehicle } from '@jetpack/interfaces'
import Head from 'next/head'
import Image from 'next/image'

import styles from '~/assets/Home.module.css'
import { VehicleCardComponent } from '~/components/card/vehicle/vehicle.component'
import { getList } from '~/services/vehicle.api'

export default function Home() {
	const [vehicles, setVehicles] = useState<IVehicle[] | null>(null)

	async function loadData() {
		const data = await getList()
		if (data) {
			setVehicles(data)
		}
	}

	useEffect(() => {
		loadData()
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>Veja seus veiculos</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Veja seus veiculos</h1>

				<p className={styles.description}>
					Lista de veiculos
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					{vehicles &&
						vehicles.map(item => (
							<VehicleCardComponent
								key={item._id}
								id={item._id}
								placa={item.placa}
								chassi={item.chassi}
								renavam={item.renavam}
								modelo={item.modelo}
								marca={item.marca}
								ano={item.ano}
							/>
						))}
				</div>
			</main>
			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}
